AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Resume challenge back end

Globals:
  Function:
    Timeout: 3
  Api:
    Cors:
      AllowMethods: "'GET,OPTIONS'"
      AllowHeaders: "'Content-Type'"
      AllowOrigin: "'*'"


Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: aws-sam-cli-managed-visitor-count

  VisitorCountFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: visitor_count/
      FunctionName: GetVisitorCount
      Description: Function to iterate visitor count using dynamoDB
      Policies:
      - AmazonDynamoDBFullAccess
      Handler: visitor_count.lambda_handler
      Runtime: python3.8
      Events:
        GetVisitorCountAPI:
          Type: Api 
          Properties:
            Path: /
            Method: get

  VisitorCountTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: website-visits
      AttributeDefinitions:
        - 
          AttributeName: "site"
          AttributeType: "S"

      KeySchema:
        - 
          AttributeName: "site"
          KeyType: "HASH"
      
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

# Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  # GetVisitorCountApi:
     # Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    # Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/visitorcount/"
  # VisitorCountFunction:
    # Description: "Hello World Lambda Function ARN"
    # Value: !GetAtt VisitorCountFunction.Arn
  #HelloWorldFunctionIamRole:
    #Description: "Implicit IAM Role created for Hello World function"
    #Value: !GetAtt HelloWorldFunctionRole.Arn
