name: Lambda Function Update
on:
  push:
    branches:
      - master
    paths:
      - 'visitor_count/*'
      - '.github/workflows/update_lambda.yml'
    #adding tags in case I add versioning later via branches
    #tags:
    #  - v1
    #  - v1.*
jobs:
  deploy-lambda:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
                  pip install -r requirements.txt
    - name: Run Unit Test
      run: |
        python3 -m unittest test_UpdateCount.py
    - name: Zip lambda function
      run: cd visitor_count && visitor_count.zip visitor_count.py
    - name: Deploy AWS Lambda function
      uses: yvesgurcan/deploy-lambda-function@master
      with:
        package: ./visitor_count/visitor_count.zip
        function-name: site-counter-dynamodb
        AWS_REGION: ${{ secrets.AWS_REGION }}
        AWS_SECRET_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

